# Generated by Django 3.1 on 2020-08-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_data',
            new_name='date',
        ),
    ]
